### ISSUE TITLE
errore installazione modulo "seedoo protocollo"

### ISSUE THREAD

**Issue by raffaelecolatrella** [seedoo/seedoo-core#10]
Dopo aver seguito scrupolosamente i passi di installazione di seedoo, in quella per l'installazione del modulo "Seedoo Protocollo" compare il seguente messaggio di errore ( a seguire l'estratto da sedoo.log) e l'installazione del modulo non viene conclusa

> 
"""
return new_api(self, *args, **kwargs)
  File "/home/user/seedoo/ocb/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
La convalida del campo(i) 'arch' non \xe8 riuscita a causa del vincolo: Invalid view definition

Dettagli dell'Errore:
L'elemento '<xpath expr="//field[@name='auth_signup_template_user_id']/..">' non pu\xf2 esser localizzato nella vista genitore

Contesto errore:
Vista 'Protocollo Settings'
[view_id: 424, xml_id: n/d, model: base.config.settings, parent_id: 217]" while parsing /home/user/seedoo/seedoo-core/seedoo_protocollo/view/res_config.xml:91, near
<record id="view_protocollo_config_settings" model="ir.ui.view">
            <field name="name">Protocollo Settings</field>
            <field name="model">base.config.settings</field>
            <field name="inherit_id" ref="base_setup.view_general_configuration"/>
            <field name="arch" type="xml">
                <xpath expr="//field[@name='auth_signup_template_user_id']/.." position="after">
                    <div>
                        <field name="auth_signup_disable_email_create_user" class="oe_inline"/>
                        <label for="auth_signup_disable_email_create_user"/>
                    </div>
                    <div>
                        <field name="auth_signup_disable_email_create_employee" class="oe_inline"/>
                        <label for="auth_signup_disable_email_create_employee"/>
                    </div>
                </xpath>
            </field>
        </record>'
"""

Ho riprovato cambiando anche /etc/default/locale della macchina ma il problema persiste.

Per testare seedoo sto utilizazndo una VM di GCP alla versione consigliata nella guida:

user@ubuntu-bionic-sedoo:~/seedoo$ uname -a Linux ubuntu-bionic-sedoo 4.15.0-1030-gcp #32-Ubuntu SMP Wed Apr 10 10:27:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Sul forum qualcuno ha avuto lo stesso problema il 09 Gennaio 2019.. ma non avuto nessuna risposta
[link al forum](https://www.seedoo.it/forum/seedoo-1/question/errore-installazione-modulo-seedoo-protocollo-36)

**Comment by raffaelecolatrella** [comment]
Attualmente ho commentato le righe del seguente file dalla 91 alla 107
/home/user/seedoo/seedoo-core/seedoo_protocollo/view/res_config.xml
in questo modo funziona, quindi direi che il problema è circoscritto alla view

**Comment by ortese** [comment]
BUG risolto nelle versioni successive
