### ISSUE TITLE
mail di notifica assegnazione protocollo non partono

### ISSUE THREAD

**Issue by ecche** [seedoo/seedoo-core#12]
la notifica di assegnazione protocollo non parte. In configurazione , funzioni tecniche, email, email , trovo la lista delle mail non partite. Hanno tutte il corpo del messaggio vuoto, nonostante il template standard (Assegnazione Documento Protocollato) preveda un contenuto. Se dalla lista delle mail non partite apro una mail, aggiungo qualsiasi carattere nel corpo del messaggio e reinvio manualmente, la mail parte.
Ho provato a modificare il template sia nell'oggetto che nel corpo ma le mail generate sono sempre uguali come se il template non venisse utulizzato

**Comment by ortese** [comment]
BUG risolto nelle versioni successive
