### ISSUE TITLE
[Proposta] Inclusione all'interno del catalogo del riuso per la PA

### ISSUE THREAD

**Issue by peppelinux** [seedoo/seedoo-core#14]
Ciao e complimenti per questo software,
Chiedo come mai non abbiate già pensato di proporre questa soluzione all'interno di:
https://developers.italia.it/it/software/

Questo è un esempio di public code che ho utilizzato all'interno di un mio progetto:
https://github.com/UniversitaDellaCalabria/uniAuth/blob/master/publiccode.yml

Sono certo che all'interno del catalogo questo software potrà ricevere le attenzioni di un pubblico abbastanza vasto.

**Comment by ortese** [comment]
Ora siamo su developers.italia.it
https://developers.italia.it/it/software/seedoo-seedoo-core-447c53
