### ISSUE TITLE
Errore nell'installazione del modulo Sedoo protocollo

### ISSUE THREAD

**Issue by gluca-innovyou** [seedoo/seedoo-core#17]
Questo il messaggio che l'interfaccia utente riporta quando si cerca di installare il modulo in oggetto:

Errore

È possibile provare a installare il modulo: "seedoo_protocollo" che dipende dal modulo: "sharedmail".
Ma quest'ultimo modulo non è disponibile nel tuo sistema.

**Comment by ortese** [comment]
cd ~/seedoo
git clone -b 8.0 https://github.com/flosslab/server-tools.git
