### ISSUE TITLE
Integrazione con odoo 10

### ISSUE THREAD

**Issue by temuccio** [seedoo/seedoo-core#3]
Salve, 
ho già un'istanza di odoo 10 su un server e vorrei integrarla con seedoo, è possibile?
Anche in questo caso è necessario scaricare i repository "ocb" e "web"?
In caso di risposta affermativa, posso utilizzare i repository della versione 10 oppure seedoo è sviluppato solo per quel branch (indicato tra l'altro con i commit di riferimento).
Grazie

**Comment by sardylan** [comment]
Al momento Seedoo è compatibile solo con la versione 8.0 di Odoo.
Purtroppo le release successive di odoo non supportano a pieno moduli scritti per versioni precedenti (in particolare dalla 8.0 in giù) senza interventi mirati sul codice.
Consiglio quindi un'installazione dedicata che utilizza, appunto, la versione 8.0 di odoo, con tutti i repository associati, come indicato nel [wiki](https://github.com/seedoo/seedoo-core/wiki/Come-Iniziare).

Il nostro team di sviluppo ha in programma una migration ad una versione più recente di odoo, ma non abbiamo ancora definito una roadmap.
