### ISSUE TITLE
Syntax error on startup

### ISSUE THREAD

**Issue by VamosErik88** [seedoo/seedoo-core#4]
Salve,

Sto provando a far girare la piattaforma Seedoo su un ambiente Linux CentOS 6.9.
Dopo aver seguito tutti i passaggi descritti nella guida allo startup ed eseguito il comando **bash seedoo-core/run.sh**, mi viene restituita questa stacktrace di errore:

`# Traceback (most recent call last):
  File "./ocb/openerp-server", line 2, in <module>
    import openerp
  File "/root/seedoo/ocb/openerp/__init__.py", line 76, in <module>
    import modules
  File "/root/seedoo/ocb/openerp/modules/__init__.py", line 27, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/root/seedoo/ocb/openerp/modules/graph.py", line 32, in <module>
    import openerp.osv as osv
  File "/root/seedoo/ocb/openerp/osv/__init__.py", line 22, in <module>
    import osv
  File "/root/seedoo/ocb/openerp/osv/osv.py", line 23, in <module>
    from .orm import Model, TransientModel, AbstractModel
  File "/root/seedoo/ocb/openerp/osv/orm.py", line 5, in <module>
    from ..models import (
  File "/root/seedoo/ocb/openerp/models.py", line 2091
    groupby_dict = {gb['groupby']: gb for gb in annotated_groupbys}
                                        ^
SyntaxError: invalid syntax`

Provando poi a raggiungere il backed alla porta suggerita (8069) non ho successo.
C'è per caso qualche problema con l'installazione nell'ambiente CentOS?

Resto in attesa di un vostro feedback.
Buona giornata

**Comment by sardylan** [comment]
Salve,
Il fatto che non raggiungi l'applicazione sulla 8069 è dovuto al fatto che il software non si è avviato in modo corretto.
Lo stacktrace inviato sembra indicare errori dovuti all'interprete python.
La procedura di installazione è stata testata su Ubuntu 16.04, e richiede un VirtualEnv per python 2.7 con specifiche dipendenze, così come indicato dalla guida.
Su CentOS dovresti assicurarti di aver installato tutte le dipendenze di sistema necessarie e di aver creato un VirtualEnv in modo corretto.

Inoltre ti sconsiglio l'esecuzione da utente ROOT. Meglio creare ed usare un utente dedicato.

**Comment by VamosErik88** [comment]
Grazie per la puntuale risposta.
In effetti facendo delle ricerche in autonomia sono giunto a delle discussioni sul framework odoo che indicavano come il problema fosse proprio la versione di python.
Dopo l'aggiornamento alla 2.7 tutto è andato liscio.
Anche per l'esecuzione ho creato un utente ad hoc.

Approfitto del'occasione per chiedervi se esiste una sorta di "manuale" d'istruzioni che spieghi come utilizzare tutte le funzionalità del protocollo.
Ad esempio oltre a protocollare da una sorgente PEC è possibile protocollare anche da una sorgente email standard?

Resto in attesa di vs feedback.
Grazie e buona giornata.

**Comment by ortese** [comment]
Le segnalazioni aperte nella sezione Issues riguardano argomenti tecnici relativi al codice sorgente dell'applicazione, a suggerimenti sull'implementazione delle funzionalità ed alla segnalazione di bug.
Vi invito ad iscrivervi sul forum dedicato, raggiungibile all'indirizzo https://forum.seedoo.it, in cui potete trovare maggior informazioni ed assistenza diretta da parte della community.

**Comment by ortese** [comment]
Le segnalazioni aperte nella sezione Issues riguardano argomenti tecnici relativi al codice sorgente dell'applicazione, a suggerimenti sull'implementazione delle funzionalità ed alla segnalazione di bug.
Vi invito ad iscrivervi sul forum dedicato, raggiungibile all'indirizzo https://forum.seedoo.it, in cui potete trovare maggior informazioni ed assistenza diretta da parte della community.
