### ISSUE TITLE
ImportError: No module named simplejson

### ISSUE THREAD

**Issue by fcapolupo** [seedoo/seedoo-core#5]
Buongiorno,
ho effettuato l'installazione come da procedura da voi descritta a questo URL https://github.com/seedoo/seedoo-core/wiki/Come-Iniziare - il sistema operativo utilizzato è quello da voi indicato nella procedura su indicata ovvero Ubuntu Server 16.04 amd64. Problema: dopo aver completato tutte le fasi di installazione dei vari pacchetti, all'avvio di Odoo tramite il comando bash seedoo-core/run.sh lo script va in errore in quanto fallisce l'import seguent:e ImportError: No module named simplejson.

Resto in attesa di un vostro riscontro. Grazie in anticipo.
Buona giornata

**Comment by sardylan** [comment]
Buongiorno,
ho appena verificato la procedura della guida e tutto sembra funzionare in modo corretto.
L'errore indicato potrebbe essere dovuto al fatto che il virtualenv non contiene le dipendenze python necessarie.
Puoi provare a verificare con **pip freeze** se tutte le dipendenze necessarie sono installate in modo corretto.

**Comment by MZorzy** [comment]
installato come da istruzioni (win7 64 + Virtualbox 5.2.6)  in ubuntu server 16.04.03 LTS 
@sardylan intendo che funziona tutto.

**Comment by sardylan** [comment]
@MZorzy anche a te stesso problema?

**Comment by fcapolupo** [comment]
Buongiorno, 
purtroppo pur avendo eseguito il comando pip freeze, l'errore ImportError: No module named simplejson persiste.

**Comment by sardylan** [comment]
Il comando `pip freeze`, eseguito all'interno del VirtualEnv, dovrebbe dare l'elenco delle librerie python installate. In questo modo è possibile verificare se simplejson è correttamente installato o meno. L'elenco dovrebbe coincidere, grosso modo, con quanto indicato dai file requirements.txt presenti sia su ocb che su seedoo.
Occorre inoltre prestare attenzione alle directory in cui ci si trova quando vengono eseguiti i comandi, per essere sicuri che si stia utilizzando il virtualnv e non python di sistema.

In ogni caso sto testando di nuovo la procedura descritta nelle guide per verificare eventuali errori.

**Comment by fcapolupo** [comment]
Salve, ho eliminato e ricreato il VirtualEnv e adesso funziona. Grazie mille!!

**Comment by Utente81** [comment]
Ciao scusa la domanda ma è la prima volta che lavoro con odoo. Sotto quale directory deve stare per avviarsi. Il postgrl si avvia e anche  il run.sh di seedoo-core , ma non riesco ad aprire la web interface.

**Comment by fcapolupo** [comment]
Ciao,
come da guida https://github.com/seedoo/seedoo-core/wiki/Come-Iniziare

Avviare Odoo usando lo script run.sh :

cd ~/seedoo
bash seedoo-core/run.sh

**Comment by Utente81** [comment]
si perfetto seguo la guida e tutto va bene ma non so se serve tipo un web server visto non conosco la piattaforma odoo. Il tutto deve stare sotto opt o quale altra directory?
Scusa ancora il disturbo

**Comment by fcapolupo** [comment]
C'è un webserver integrato in Odoo, sempre come da guida:

Una volta avviato Odoo collegarsi via browser al backend tramite l'indirizzo http://<address>:8069, dove address è l'indirizzo della macchina.

**Comment by Utente81** [comment]
perfetto  proprio quello che non riesco ad aprire non mi si apre appure il servizio parte

**Comment by fcapolupo** [comment]
verifica il firewall di linux...

**Comment by Utente81** [comment]
Nulla non parte grazie dell aiuto potrei chiederti quali pacche a parte quelli della guida hai installato?

**Comment by fcapolupo** [comment]
Solo quelli della guida ed il sistema operativo è GNU/Linux Ubuntu Server 16.04 amd64.

**Comment by Utente81** [comment]
La directory dove hai messo Seedoo?

**Comment by Utente81** [comment]
installo ubuntu come da guida con postgre, seguo la guida passo passo creo la dir seedoo nella home dell utente scarico tutto creo utente post avvio con run.sh (firewall disabilitato) e non ne vuole sapere di partire dal web. Possibili soluzioni?
PS: se installo odoo su server dedicato funziona e me lo trovo sotto la dir /opt.

**Comment by fcapolupo** [comment]
Ciao, qualcosa non fai correttamente... segui con attenzione la guida.

**Comment by sardylan** [comment]
Le segnalazioni aperte nella sezione Issues riguardano argomenti tecnici relativi al codice sorgente dell'applicazione, a suggerimenti sull'implementazione delle funzionalità ed alla segnalazione di bug.
Vi invito ad iscrivervi sul forum dedicato, raggiungibile all'indirizzo https://forum.seedoo.it, in cui potete trovare maggior informazioni ed assistenza diretta da parte della community.
