### ISSUE TITLE
seedoo

### ISSUE THREAD

**Issue by Utente81** [seedoo/seedoo-core#6]
Buoasera nonostante abbia provato con sistemi diversi (ubuntu 16 e Centos 7), applicando il codice e la configurazione da voi pubblicata, la piattaforma Odoo non si avvia, dando errore   Import Error: No module named simplejson.

**Comment by sardylan** [comment]
Vedi issue #5

**Comment by Utente81** [comment]
installo ubuntu come da guida con postgre, seguo la guida passo passo creo la dir seedoo nella home dell utente scarico tutto creo utente post avvio con run.sh (firewall disabilitato) e non ne vuole sapere di partire dal web. Possibili soluzioni?
PS: se installo odoo su server dedicato funziona e me lo trovo sotto la dir /opt.

**Comment by sardylan** [comment]
In caso di errore lo script dovrebbe stampare sul terminale uno StackTrace.
Prova a postare qui eventuali errori, controllando anche il contenuto del file seedoo.log nella HOME dell'utente.

**Comment by Utente81** [comment]
lo script si avvia senza nessun errore ma nei log non riesco a capire perchè openerp.service non hà indirizzo
allego 
![seedoo](https://user-images.githubusercontent.com/36738123/36719496-7af7bdac-1ba5-11e8-8920-8955c04609f5.PNG)

**Comment by sardylan** [comment]
Dallo screenshot allegato, il server web interno di Odoo è correttamente avviato.
L'indirizzo di listening 0.0.0.0:8069 indica che il binding della porta 8069 è effettuato su tutte le interfacce della macchina.
Ora, come indicato dalla guida, se il server dispone di un desktop è possibile raggiungere il portale su http://127.0.0.1:8069. Se si accede invece da un'altra macchina della rete, occorre andare all'indirizzo http://<ip_address>:8069, dove <ip_address> è l'indirizzo IP del server che ospita l'installazione di Seedoo.

Per ulteriori informazioni consiglio di utilizzare il forum dedicato disponibile all'indirizzo http://forum.seedoo.it/

**Comment by Utente81** [comment]
tutto fatto gia e non solo una volta cmq grazie mille per il supporto.
